package org.yiuos.home;

/** Resource IDs generated by aapt in a real platform build. */
public final class R {
    public static final class string {
        public static final int ready = 0x7f010001;
        public static final int privacy_summary = 0x7f010002;

        private string() {
        }
    }

    private R() {
    }
}
