LOCAL_PATH := vendor/yiuos/legacy/hinoki

# The launcher is the device-visible implementation of the interactive
# prototype: YiuOS home, status card, app dock and privacy/control surface.
PRODUCT_PACKAGES += \
    YiuHome

# Ship YiuHome as the only preinstalled HOME activity.
PRODUCT_PACKAGES := $(filter-out Trebuchet,$(PRODUCT_PACKAGES))

# Generated by tools/hinoki/prepare-assets.sh before the Android build starts.
PRODUCT_PACKAGE_OVERLAYS += \
    $(LOCAL_PATH)/generated/overlay

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/generated/bootanimation.zip:system/media/bootanimation.zip

PRODUCT_PROPERTY_OVERRIDES += \
    ro.yiuos.version=0.3-hinoki \
    ro.yiuos.build.version=15.1 \
    ro.yiuos.releasetype=UNOFFICIAL \
    ro.yiuos.device=hinoki \
    ro.com.google.clientidbase=android-sony
